import PageLayout from '@/components/layouts/PageLayout'
import TopNavigation from '@/components/navigation/TopNavigation'
import { ClockIcon } from '@heroicons/react/24/outline'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import dayjs from 'dayjs'
import { Pin } from '@icon-park/react'
import { useVenuesStore } from '@/store/venueStore'
import utc from 'dayjs/plugin/utc'
import timezone from 'dayjs/plugin/timezone'

dayjs.extend(utc)
dayjs.extend(timezone)
dayjs().format()

export default function EventDetailPage() {
  const router = useRouter()
  const { id } = router.query
  const { fetchVenue, activeVenue } = useVenuesStore()
  const today = dayjs().utc();
  useEffect(() => {
    id && fetchVenue(id, today.format('YYYY-MM-DD'))
  }, [id])

  return (
    <div className='bg-neutral-50 min-h-screen pb-10'>
      <Head>
        <title>{activeVenue?.title || activeVenue?.name || 'Find events on Fesa.app'} | Fesa.app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopNavigation />
      <PageLayout>
        <div className='flex items-center justify-center flex-col w-full rounded'>
          {/*<div className='md:h-[420px] md:bg-contain bg-cover md:bg-no-repeat h-[220px] bg-neutral-200 w-full rounded'
            style={{
              backgroundImage: `url('${activeVenue?.image || 'https://placekitten.com/500/500'}')`,
              //backgroundSize: 'cover',
              backgroundPosition: 'center center'
            }}
          />*/}
          <div className='space-y-2 w-full bg-white shadow-md md:p-4 p-2 my-2 rounded'>
            <h1 className='md:text-3xl text-xl font-semibold'>{activeVenue?.name}</h1>
            <p className='md:text-md text-sm'>{activeVenue?.description}</p>

            <div className='flex items-center justify-start space-x-1 text-neutral-600 text-md'>
              <Pin className='w-5 h-5' />
              <p className='capitalize text-md'>{activeVenue?.name}, {activeVenue?.city}, {activeVenue?.country}</p>
            </div>

          </div>

          <div className='w-full bg-white shadow-md my-2 rounded'>
            <h2 className='text-xl font-semibold p-4 px-2'>Events at {activeVenue?.name}</h2>
            {activeVenue?.events?.length === 0 ? (
              <div className='p-4 px-2'>
                <p>No events found at {activeVenue?.name}</p>
              </div>
            ) : <>
              {activeVenue?.events?.map((event, index) => (
                <div
                  onClick={() => router.push(`/events/${event.internal_id}`)}
                  className='grid md:grid-cols-2 grid-cols-1 border-t gap-2 sm:h-16 py-2 px-2 hover:bg-pink-50 cursor-pointer'
                  key={index}
                >
                  <div className='flex items-center justify-start gap-2 border-neutral-200  col-span-1' >
                    <ClockIcon className='w-5 h-5' />
                    <p className='text-md'>{dayjs(event.date || event.start_date).format('dddd, DD MMMM YYYY')}</p>
                  </div>
                  <div className='col-span-1 flex items-center justify-start'>
                    <p className='font-semibold'>{event.title || event.name}</p>
                  </div>
                </div>
              ))}
            </>
            }
          </div>
        </div>
      </PageLayout >
    </div >
  )
}
