import Tabs from '@/components/navigation/Tabs'
import TopNavigation from '@/components/navigation/TopNavigation'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TopNavigation />
      <div className="mx-auto max-w-6xl px-6 lg:px-8">
        <Tabs />
      </div>
    </>
  )
}
