import PageLayout from '@/components/layouts/PageLayout'
import TopNavigation from '@/components/navigation/TopNavigation'
import { ClockIcon } from '@heroicons/react/24/outline'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import dayjs from 'dayjs'
import { Pin } from '@icon-park/react'
import { useEventsStore } from '@/store/eventsStore'
dayjs().format()

export default function EventDetailPage() {
  const { event, isLoading, activeEvent, fetchEvent } = useEventsStore()
  const router = useRouter()
  const { id } = router.query

  useEffect(() => {
    id && fetchEvent(id)
  }, [id])

  return (
    <div className='bg-neutral-50 min-h-screen pb-10'>
      <Head>
        <title>{activeEvent?.title || activeEvent?.name || 'Find events on Fesa.app'} | Fesa.app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopNavigation />
      {/*{JSON.stringify(event, null, 2)}*/}
      <PageLayout>
        <div className='flex items-center justify-center flex-col w-full md:p-4 p-2 my-4 bg-white shadow-md rounded-md'>
          <div className='h-[420px] bg-neutral-200 w-full rounded-md'
            style={{
              backgroundImage: `url('${activeEvent?.image || 'https://placekitten.com/500/500'}')`,
              backgroundSize: 'cover',
              backgroundPosition: 'center center'
            }}
          />
          <div className='space-y-4 md:py-8 py-4 w-full'>
            <h1 className='text-3xl'>{activeEvent?.name}</h1>
            <p className='text-md'>{activeEvent?.description}</p>
            <div className='flex items-center justify-start space-x-2 text-neutral-600 text-md'>
              <ClockIcon className='w-5 h-5' />
              <p>{dayjs(activeEvent?.start_date).format('dddd, DD MMMM YYYY')}</p>
            </div>
            <div className='flex items-center justify-start space-x-2 text-neutral-600 text-md'>
              <Pin className='w-5 h-5' />
              <p className='capitalize'>{activeEvent?.venues?.name}, {activeEvent?.venues?.city}, {activeEvent?.venues?.country}</p>
            </div>
            <div className='border rounded-md hover:bg-neutral-100 cursor-pointer 
            min-h-16 p-2 flex items-center justify-start space-x-4'>
              <div className='flex items-center justify-center 
              w-14 h-14 bg-neutral-100 rounded-full'>
              </div>
              <div>
                <p>{activeEvent?.organisator || activeEvent?.venue}</p>
                <p className='text-neutral-500'>{activeEvent?.phone || '+12 345-789'}</p>
              </div>
            </div>
          </div>
        </div>
      </PageLayout>
    </div>
  )
}
