import PageLayout from '@/components/layouts/PageLayout'
import TopNavigation from '@/components/navigation/TopNavigation'
import { ArrowLeftIcon, ClockIcon } from '@heroicons/react/24/outline'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import dayjs from 'dayjs'
import { ArrowLeft, Pin } from '@icon-park/react'
import { useEventsStore } from '@/store/eventsStore'
dayjs().format()

export default function EventDetailPage() {
  const { event, isLoading, activeEvent, fetchEvent } = useEventsStore()
  const router = useRouter()
  const { id } = router.query

  useEffect(() => {
    id && fetchEvent(id)
  }, [id])

  return (
    <div className='bg-neutral-50 min-h-screen pb-10'>
      <Head>
        <title>{activeEvent?.title || activeEvent?.name || 'Find events on Fesa.app'} | Fesa.app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopNavigation />
      <PageLayout>
        <div className='flex items-center justify-start w-full pb-2'>
          <button
            onClick={() => router.back()}
            className='text-neutral-600 text-md rounded-full p-2 bg-neutral-100'>
            <ArrowLeftIcon className='w-5 h-5' />
          </button>
        </div>
        <div className='flex items-center justify-center flex-col w-full rounded'>
          <div className='md:h-[420px] md:bg-contain bg-cover md:bg-no-repeat h-[220px] bg-neutral-200 w-full rounded'
            style={{
              backgroundImage: `url('${activeEvent?.image || 'https://placekitten.com/500/500'}')`,
              //backgroundSize: 'cover',
              backgroundPosition: 'center center'
            }}
          />
          <div className='space-y-4 w-full bg-white shadow-md md:p-4 p-2 my-2 rounded'>
            <h1 className='md:text-3xl text-xl font-semibold'>{activeEvent?.name}</h1>
            <p className='md:text-md text-sm'>{activeEvent?.description}</p>
            <div className='flex items-center justify-start space-x-2 text-neutral-600 text-md'>
              <ClockIcon className='w-5 h-5' />
              <p className='md:text-md text-sm'>{dayjs(activeEvent?.start_date).format('dddd, DD MMMM YYYY')}</p>
            </div>
            <div className='flex items-center justify-start space-x-2 text-neutral-600 text-md'>
              <Pin className='w-5 h-5' />
              <p className='capitalize md:text-md text-sm'>{activeEvent?.venues?.name}, {activeEvent?.venues?.city}, {activeEvent?.venues?.country}</p>
            </div>
            <div className='border rounded hover:bg-neutral-100 cursor-pointer 
            min-h-16 p-2 flex items-center justify-start space-x-4'>
              <div className='flex items-center justify-center 
              w-14 h-14 bg-neutral-100 rounded-full'>
              </div>
              <div className='md:text-md text-sm'>
                <p>{activeEvent?.organisator || activeEvent?.venue}</p>
                <p className='text-neutral-500'>{activeEvent?.phone || '+12 345-789'}</p>
              </div>
            </div>
          </div>
        </div>
      </PageLayout >
    </div >
  )
}
