import DiscoverHeader from '@/components/headers/DiscoverHeader'
import PageLayout from '@/components/layouts/PageLayout'
import Footer from '@/components/navigation/Footer'
import Tabs from '@/components/navigation/Tabs'
import TopNavigation from '@/components/navigation/TopNavigation'
import EventsStack from '@/components/stack/EventsStack'
import Head from 'next/head'

export default function EventsPage() {
  return (
    <>
      <Head>
        <title>Events near me | Fesa.app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DiscoverHeader />
      <PageLayout>
        <EventsStack />
      </PageLayout>
      <Footer />
    </>
  )
}
