import DiscoverHeader from '@/components/headers/DiscoverHeader'
import PageLayout from '@/components/layouts/PageLayout'
import Footer from '@/components/navigation/Footer'
import Tabs from '@/components/navigation/Tabs'
import TopNavigation from '@/components/navigation/TopNavigation'
import EventsStack from '@/components/stack/EventsStack'
import Head from 'next/head'
import dayjs from 'dayjs'
import { useEffect, useState } from 'react'
import { useEventsStore } from '@/store/eventsStore'
dayjs().format()

export default function EventsPage() {
  const [startingDate, setStartingDate] = useState(dayjs().format('YYYY-MM-DD'))
  const [endingDate, setEndingDate] = useState(dayjs().add(1, 'day').format('YYYY-MM-DD'))
  const [city, setCity] = useState("")
  const [page, setPage] = useState(0)
  const { fetchEvents, isLoading, fetchEventsNewPage } = useEventsStore()

  const handleSearch = async () => {
    console.log('searching...',
      city, startingDate, endingDate
    )
    await fetchEvents({
      city: city,
      startingDate: dayjs(startingDate).toISOString(),
      endingDate: dayjs(endingDate).toISOString(),
      page: page,
    })
  }

  const handleSearchNewPage = async () => {
    console.log('searching...',
      city, startingDate, endingDate
    )
    await fetchEventsNewPage({
      city: city,
      startingDate: dayjs(startingDate).toISOString(),
      endingDate: dayjs(endingDate).toISOString(),
      page: page,
    })
  }

  useEffect(() => {
    handleSearch()
  }, [city, startingDate])

  useEffect(() => {
    handleSearchNewPage()
  }, [page])

  return (
    <>
      <Head>
        <title>Events near me | Fesa.app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DiscoverHeader
        startingDate={startingDate}
        setStartingDate={setStartingDate}
        city={city}
        setCity={setCity}
      />
      <PageLayout>
        <EventsStack />
        <button
          disabled={isLoading}
          onClick={() => setPage(page + 1)}
          className='py-2 bg-black text-white px-4 rounded w-full hover:bg-pink-500 text-sm'>
          {isLoading ? 'Loading...' : 'Load More'}
        </button>
      </PageLayout>
      <Footer />
    </>
  )
}
